(use-package :wxCL)
;(use-package :wxEvent)
(use-package :wxframe)
(use-package :wxPanel)
(use-package :wxSizer)
(use-package :wxWindow)
(use-package :wx_wrapper)
(use-package :wx_main)
(use-package :wxIcon)
(use-package :wxButton)
(use-package :wxCheckBox)
(use-package :wxCheckListBox)
(use-package :wxRadioButton)
(use-package :wxRadioBox)
(use-package :wxListBox)
(use-package :wxSpinCtrl)
(use-package :wxNotebook)
(use-package :wxChoice)
(use-package :wxComboBox)
(use-package :wxTreeCtrl)
(use-package :wxListCtrl)

(load "../clisp-wrappers/wxStaticText.lisp")
(load "../clisp-wrappers/wxStaticBox.lisp")
(load "../clisp-wrappers/wxCalendarCtrl.lisp")
(load "../clisp-wrappers/wxGauge.lisp")
(load "../clisp-wrappers/wxStaticLine.lisp")
(load "../clisp-wrappers/wxToggleButton.lisp")

(defun add-top-controls (sizer panel)
   (let* ((lisp-text (wxStaticText:wxcl-create-static-text panel "Choose your lisp"))
	  (static-box (wxStaticBox:wxcl-create-static-box panel "Optional choices" :width 100 :height 100))
	  (rd-clisp (wxradiobutton_create panel -1 "CLISP" -1 -1 -1 -1 wxRB_GROUP))
	  (rd-sbcl (wxradiobutton_create panel -1 "SBCL" -1 -1 -1 -1 0))
	  (chk-verbose (wxcl-create-Check-Box panel "Verbose"))
	  (chk-log (wxcl-create-Check-Box panel "Log"))
	  (lst-vars (wxcl-create-list-box panel (vector "frame" "window" "world")))
	  (top-sizer (wxboxsizer_create wxHORIZONTAL))
	  (bottom-sizer (wxboxsizer_create wxHORIZONTAL))
	  (cal-ctrl (wxCalendarCtrl:wxcl-create-calendar-control panel))
	  (gauge (wxGauge:wxcl-create-gauge panel 300)))
     (wxsizer_addwindow top-sizer lisp-text 0 0 100 nil)
     (wxsizer_addwindow top-sizer rd-clisp 0 0 100 nil)
     (wxsizer_addwindow top-sizer rd-sbcl 0 0 100 nil)
     (wxsizer_addwindow top-sizer static-box 0 0 100 nil)
     (wxsizer_addwindow top-sizer chk-log 0 0 100 nil)
     (wxsizer_addwindow top-sizer chk-verbose 0 0 100 nil)
     (wxsizer_addSizer sizer top-sizer 0 0 0 nil)
     (wxsizer_addSizer sizer bottom-sizer 0 0 0 nil)
     (wxsizer_addwindow bottom-sizer lst-vars 0 0 100 nil)
     (wxsizer_addwindow bottom-sizer cal-ctrl 0 0 100 nil)
     (wxsizer_addwindow bottom-sizer gauge 0 0 100 nil)
     (wxGauge:wxGauge_SetValue gauge 150)))

(defun add-bottom-controls (sizer panel)
  (let ((top-sizer (wxboxsizer_create wxHORIZONTAL))
	(bottom-sizer (wxboxsizer_create wxHORIZONTAL))
	(btn-exec (wxcl-create-button panel "Execute"))
	(btn-clear (wxcl-create-Button panel "Clear"))
	(lisp-group (wxcl-create-radio-box panel "Lisp" (vector "sbcl" "clisp")))
 	(chk-lst (wxcl-create-check-list-box panel (vector "frame" "window" "world")))
 	(spin (wxcl-create-spin-control panel 0 10))
 	(choice (wxcl-create-choice panel (vector "clisp" "sbcl" "allegro")))
 	(combo (wxcl-create-combo-box panel (vector "clisp" "sbcl" "allegro") :value "default"))
 	(root (wxTreeItemID_Create))
 	(branch (wxTreeItemID_Create))
 	(tree (wxcl-create-tree-control panel))
	(tgl (wxToggleButton:wxcl-create-toggle-button panel "Toggle me"))
	)
     (wxTreeCtrl_AddRoot tree "Hello Tree" -1 -1 nil root)
     (wxTreeCtrl_AppendItem tree root "branch1" -1 -1 nil branch)
     (wxsizer_addwindow bottom-sizer btn-clear 0 0 100 nil)
     (wxsizer_addwindow bottom-sizer btn-exec 0 0 100 nil)
     (wxsizer_addwindow top-sizer lisp-group 0 0 100 nil)
     (wxsizer_addWindow top-sizer choice 0 0 100 nil)
     (wxsizer_addWindow top-sizer combo 0 0 100 nil)
     (wxsizer_addwindow top-sizer chk-lst 0 0 100 nil)
     (wxsizer_addwindow top-sizer spin 0 0 100 nil)
     (wxsizer_addwindow top-sizer tree 0 0 100 nil)
     (wxsizer_addwindow bottom-sizer tgl 0 0 100 nil)
     (wxsizer_addSizer sizer top-sizer 0 0 0 nil)
     (wxsizer_addSizer sizer bottom-sizer 0 0 0 nil)))

(defun add-controls(frame)
  (let ((main-sizer (wxboxsizer_create wxVERTICAL))
	(top-sizer (wxboxsizer_create wxVERTICAL))
	(bottom-sizer (wxboxsizer_create wxVERTICAL))
	txt nb line)
    (setf nb (wxCL-create-notebook frame))
    (setf panel (wxPanel_Create nb -1 -1 -1 -1 -1 wxTAB_TRAVERSAL))
    (print (wxNotebook_AddPage nb panel "Unknown" 1 -1))
    (print (wxNotebook_AddPage nb panel "Unknown" 1 -1))
    (wxwindow_setsizer panel main-sizer)
    (add-top-controls top-sizer panel)
    (add-bottom-controls bottom-sizer panel)
    (wxsizer_addSizer main-sizer top-sizer 0 0 0 nil)
    (setf line (wxStaticLine:wxcl-create-static-line panel :height 10))
    (setf txt (wxTextCtrl:wxcl-create-text-control panel :style wxTextCtrl:wxTE_MULTILINE :height 100))
    (wxsizer_addWindow main-sizer line 0 0 0 nil)
    (wxsizer_addSizer main-sizer bottom-sizer 0 0 0 nil)
    (wxsizer_addWindow main-sizer txt 0 0 0 nil)
    (wxsizer_fit main-sizer panel)
    (wxsizer_setsizehints main-sizer panel)))

(defun init-func (fun data evt)
  (let ((frame (wxframe_create nil -1 "wxCL - Lisp Interpreter" 10 10 700 600 wxDefault_Frame_Style)))
    (wxFrame_SetIcon frame (wxicon_createload "wxcl-logo-60.ico" wxBITMAP_TYPE_ICO -1 -1))
    (add-controls frame)
    (wxwindow_show frame)
    (print (wxDirDialog:wxcl-get-dir frame))
;    (begin-loop)
;    (repl)
;    (eljapp_Exit)
;    (ELJApp_ExitMainLoop)
    ))
;(Eljapp_initializeC (wxclosure_Create (function init-func) nil) 0 nil)

