;;;compile-all.lisp
;;;License  : GNU General Public License (GPL)
;;;Author(s) : Andre Vargas Abs da Cruz (andrev@ele.puc-rio.br)
;;;Copyright (C) 2005 Andre Vargas Abs da Cruz
;;;See the file LICENSE for information on usage and redistribution.

;; This file is used to compile all lisp wrappers for wxCL. It is used 
;; instead of asdf because, asdf tries to load the files
;; after compiling them. As we can't reference the DLL's in order to
;; generate the .c files, CLISP complains about a foreign function that
;; doesn't exist when this happens.

(compile-file "constants.lisp")
(compile-file "wxCL.lisp")
(compile-file "wxWindow.lisp")
(compile-file "wxAcceleratorEntry.lisp")
(compile-file "wxArtProvider.lisp")
(compile-file "wxBitmap.lisp")
(compile-file "wxBrush.lisp")
(compile-file "wxBusyInfo.lisp")
(compile-file "wxButton.lisp")
(compile-file "wxDateTime.lisp")
(compile-file "wxCalendarCtrl.lisp")
(compile-file "wxCaret.lisp")
(compile-file "wxCheckBox.lisp")
(compile-file "wxCheckListBox.lisp")
(compile-file "wxChoice.lisp")
(compile-file "wxClipboard.lisp")
(compile-file "wxColour.lisp")
(compile-file "wxColourData.lisp")
(compile-file "wxDialog.lisp")
(compile-file "wxColourDialog.lisp")
(compile-file "wxComboBox.lisp")
(compile-file "wxCommand.lisp")
(compile-file "wxConfigBase.lisp")
(compile-file "wxContextHelp.lisp")
(compile-file "wxControl.lisp")
(compile-file "wxCursor.lisp")
(compile-file "wxDC.lisp")
(compile-file "wxDCSVG.lisp")
(compile-file "wxDND.lisp")
(compile-file "wxDataFormat.lisp")
(compile-file "wxDialup.lisp")
(compile-file "wxDirDialog.lisp")
(compile-file "wxDrawing.lisp")
(compile-file "wxEvent.lisp")
(compile-file "wxEvtHandler.lisp")
(compile-file "wxFL.lisp")
(compile-file "wxFileDialog.lisp")
(compile-file "wxFileHist.lisp")
(compile-file "wxFindReplaceDialog.lisp")
(compile-file "wxFont.lisp")
(compile-file "wxFontData.lisp")
(compile-file "wxFontDialog.lisp")
(compile-file "wxFrame.lisp")
(compile-file "wxGauge.lisp")
(compile-file "wxGizmos.lisp")
(compile-file "wxGrid.lisp")
(compile-file "wxGrid_h.lisp")
(compile-file "wxHelpController.lisp")
(compile-file "wxIPC.lisp")
(compile-file "wxIcon.lisp")
(compile-file "wxIconBundle.lisp")
(compile-file "wxImage.lisp")
(compile-file "wxImageList.lisp")
(compile-file "wxJoystick.lisp")
(compile-file "wxLayoutConstraints.lisp")
(compile-file "wxListBox.lisp")
(compile-file "wxListCtrl.lisp")
(compile-file "wxLocale.lisp")
(compile-file "wxLog.lisp")
(compile-file "wxMDI.lisp")
(compile-file "wxMask.lisp")
(compile-file "wxMenuItem.lisp")
(compile-file "wxMenu.lisp")
(compile-file "wxMenubar.lisp")
(compile-file "wxMessageDialog.lisp")
(compile-file "wxMime.lisp")
(compile-file "wxMiniFrame.lisp")
(compile-file "wxNotebook.lisp")
(compile-file "wxPalette.lisp")
(compile-file "wxPanel.lisp")
(compile-file "wxPen.lisp")
(compile-file "wxPlot.lisp")
(compile-file "wxPrintDialog.lisp")
(compile-file "wxProcess.lisp")
(compile-file "wxRC.lisp")
(compile-file "wxRadioBox.lisp")
(compile-file "wxRadioButton.lisp")
(compile-file "wxRegion.lisp")
(compile-file "wxRegionIterator.lisp")
(compile-file "wxSash.lisp")
(compile-file "wxScintilla.lisp")
(compile-file "wxScrollBar.lisp")
(compile-file "wxScrolledWindow.lisp")
(compile-file "wxSingleInstanceChecker.lisp")
(compile-file "wxSizer.lisp")
(compile-file "wxSlider.lisp")
(compile-file "wxSpinCtrl.lisp")
(compile-file "wxSplitterWindow.lisp")
(compile-file "wxStaticBox.lisp")
(compile-file "wxStaticLine.lisp")
(compile-file "wxStaticText.lisp")
(compile-file "wxStatusBar.lisp")
(compile-file "wxSystemSettings.lisp")
(compile-file "wxTextCtrl.lisp")
(compile-file "wxThread.lisp")
(compile-file "wxTimer.lisp")
(compile-file "wxTipWindow.lisp")
(compile-file "wxToggleButton.lisp")
(compile-file "wxToolbar.lisp")
(compile-file "wx_wrapper.lisp")
(compile-file "wx_main.lisp")
(compile-file "wxTreeCtrl.lisp")
(compile-file "wxValidator.lisp")
(compile-file "wxWizard.lisp")
(compile-file "wx_scintilla.lisp")